/**
 * Types for EVM wallet portfolio integration with EIP-712 signatures
 */

import type {
  Address,
  AbiTypeToPrimitiveType as EVM_T,
  TypedDataDomain,
} from 'abitype';
import type { TargetAllocation } from './evm/ymax-eip712.ts';
import type { PermitTransferFrom } from './evm/permit2/signatureTransfer';
import type { Bech32Address } from '@agoric/cosmic-proto/address-hooks.js';

export { type TargetAllocation };

/**
 * Combined signed data for submission
 * Uses Permit2 PermitBatchTransferFrom type (array of permitted tokens)
 */
export interface SignedOpenPortfolio {
  signedPermit: {
    chainId: NonNullable<TypedDataDomain['chainId']>;
    permitSignature: EVM_T<'bytes'>;
    permit: Readonly<PermitTransferFrom>;
    witness: EVM_T<'bytes32'>;
    // generated by EVM handler, not sent from UI
    witnessTypeString: string;
  };
  owner: Bech32Address;
  allocations: readonly TargetAllocation[];
  deposit: {
    // chainId, token identify USDC contract
    chainId: bigint;
    token: Address;
    amount: bigint;
  };
}
